apiVersion: v1
data:
  .dockerconfigjson: hash_gerado_tipo_base64
kind: Secret
metadata:
  creationTimestamp: "2026-07-20T21:59:21Z"
  name: docker-registry-secret
  namespace: default
  resourceVersion: "576856"
  uid: ab9451d7-5e43-4c40-afb7-2de89ca2d35c
type: kubernetes.io/dockerconfigjson